[2022-12-10 10:37:51,331] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:37:58,379] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10137
[2022-12-10 10:38:00,568] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:38:00,883] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 3}
[2022-12-10 10:38:00,884] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:01,639] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:38:01,956] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 4}
[2022-12-10 10:38:01,957] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:02,607] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10137
[2022-12-10 10:38:02,846] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 5}
[2022-12-10 10:38:02,847] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:03,677] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"clear"}'
[2022-12-10 10:38:03,865] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 5}
[2022-12-10 10:38:03,866] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:05,345] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10137
[2022-12-10 10:38:05,383] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:05,387] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:06,550] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:06,551] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:23,107] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:38:25,070] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:25,071] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:26,879] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:38:29,268] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:29,269] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:37,162] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:38,474] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:38,476] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:38,531] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:38,958] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:39,294] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:39,601] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:39,780] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:39,781] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:40,333] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:40,334] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:40,665] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:40,666] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:40,970] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:40,971] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:52,177] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:53,189] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:53,608] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:53,931] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:54,163] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:54,164] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:54,327] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:54,328] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:54,799] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:54,800] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:55,311] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:55,312] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:39:23,129] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:39:24,615] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:39:24,616] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:39:25,096] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:39:26,317] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:39:26,318] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:01,366] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:40:05,294] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:05,789] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:07,217] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 2}
[2022-12-10 10:40:07,218] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:07,788] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/count
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '1' for key 'PRIMARY'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 33, in counter
    rsp = update_count(request)
  File "/app/wxcloudrun/views.py", line 78, in update_count
    data.save()
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry '1' for key 'PRIMARY'")
[2022-12-10 10:40:07,800] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/count HTTP/1.1" 500 209030
[2022-12-10 10:40:08,861] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:40:10,181] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 2}
[2022-12-10 10:40:10,183] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:10,942] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:12,369] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 4}
[2022-12-10 10:40:12,370] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:12,981] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:13,855] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:14,197] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 6}
[2022-12-10 10:40:14,198] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:14,941] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:15,009] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 8}
[2022-12-10 10:40:15,010] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:15,716] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:16,148] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 10}
[2022-12-10 10:40:16,149] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 23
[2022-12-10 10:40:16,711] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:16,967] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 12}
[2022-12-10 10:40:16,968] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 23
[2022-12-10 10:40:18,164] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:40:18,165] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 23
[2022-12-10 10:40:19,436] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:41:02,637] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:41:03,501] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:41:04,302] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:41:04,385] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:04,386] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:41:04,449] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:04,450] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:41:05,710] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:05,711] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:41:14,934] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10143
[2022-12-10 10:41:16,218] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:16,219] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:41:17,709] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:41:19,117] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:19,117] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:42:51,763] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:43:54,478] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:43:55,742] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:43:58,858] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:05,367] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:07,255] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:14,872] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:22,228] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:23,825] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:27,485] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 14, in index
    return render(request, 'index.html')
  File "/root/.local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/root/.local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[2022-12-10 10:44:27,491] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 72519
[2022-12-10 10:44:27,675] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 14, in index
    return render(request, 'index.html')
  File "/root/.local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/root/.local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[2022-12-10 10:44:27,678] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 72319
[2022-12-10 10:44:47,906] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:51,221] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:44:51,375] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 10140
[2022-12-10 10:45:52,975] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:00:04,253] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:01:13,836] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:01:27,600] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: index() takes 1 positional argument but 2 were given
[2022-12-10 12:01:27,603] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 54319
[2022-12-10 12:01:27,813] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: index() takes 1 positional argument but 2 were given
[2022-12-10 12:01:27,814] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 54223
[2022-12-10 12:01:59,876] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:02:01,716] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10143
[2022-12-10 12:02:01,916] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 10143
[2022-12-10 12:02:03,555] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/count
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view wxcloudrun.views.index didn't return an HttpResponse object. It returned None instead.
[2022-12-10 12:02:03,556] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/count HTTP/1.1" 500 59183
[2022-12-10 12:07:17,780] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view wxcloudrun.views.index didn't return an HttpResponse object. It returned None instead.
[2022-12-10 12:07:17,781] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 58467
[2022-12-10 12:10:17,244] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view wxcloudrun.views.index didn't return an HttpResponse object. It returned None instead.
[2022-12-10 12:10:17,245] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57735
[2022-12-10 12:10:39,685] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view wxcloudrun.views.index didn't return an HttpResponse object. It returned None instead.
[2022-12-10 12:10:39,686] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57735
[2022-12-10 12:11:31,913] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view wxcloudrun.views.index didn't return an HttpResponse object. It returned None instead.
[2022-12-10 12:11:31,914] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57745
[2022-12-10 12:12:06,105] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view wxcloudrun.views.index didn't return an HttpResponse object. It returned None instead.
[2022-12-10 12:12:06,106] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57745
[2022-12-10 12:12:35,604] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:12:36,706] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:12:37,747] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:12:40,443] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:12:43,067] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:12:44,920] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:12:46,476] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:12:49,381] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 16, in index
    print(list = request.POST)
TypeError: 'list' is an invalid keyword argument for print()
[2022-12-10 12:12:49,386] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 56644
[2022-12-10 12:13:01,967] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:13:03,912] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 10143
[2022-12-10 12:13:16,198] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:13:17,328] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:13:19,516] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:13:20,947] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:13:26,476] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 10143
[2022-12-10 12:13:39,246] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:13:41,669] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 10143
[2022-12-10 12:14:12,340] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:14:23,332] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:14:28,778] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 12:14:33,543] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 12:24:07,305] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 12:26:15,575] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:26:41,061] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:26:42,473] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:26:46,965] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:26:48,893] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:26:52,100] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:26:59,440] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:05,996] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:14,432] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:16,462] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:17,662] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:19,655] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:22,353] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:29,754] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:33,184] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:52,752] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/models.py changed, reloading.
[2022-12-10 12:27:53,413] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:54,823] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:56,877] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:27:57,929] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:04,671] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:05,827] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:07,957] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:12,909] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:21,296] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:33,532] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:36,900] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:45,212] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:51,854] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:54,138] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:58,281] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:28:59,656] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:29:26,504] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:29:28,818] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/models.py changed, reloading.
[2022-12-10 12:29:29,501] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:29:38,367] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:29:40,160] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:29:45,200] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:29:46,953] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:29:53,057] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:29:59,845] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:04,365] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:08,156] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:09,463] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:12,804] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:16,103] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:21,581] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:28,086] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:30,552] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:31,826] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:35,522] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:36,531] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:43,629] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:45,411] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:48,722] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/models.py changed, reloading.
[2022-12-10 12:30:49,532] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:54,150] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:30:57,089] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:00,189] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:01,471] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:03,171] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:05,166] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:06,768] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:10,204] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:12,779] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:14,565] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:17,880] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/models.py changed, reloading.
[2022-12-10 12:31:18,595] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:20,445] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:22,652] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:24,014] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:27,247] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:31,625] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:33,830] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:46,109] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:51,482] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:53,841] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:31:57,771] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:06,651] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:09,181] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:17,123] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:20,318] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:21,891] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:26,989] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:30,980] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:34,464] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:36,964] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:39,502] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:42,281] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:32:44,777] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:33:13,097] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:33:16,306] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/models.py changed, reloading.
[2022-12-10 12:33:17,095] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:33:18,234] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:34:14,477] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:34:16,281] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:34:28,109] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:34:29,696] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:34:58,858] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:02,558] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:09,489] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:11,400] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:12,575] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/models.py changed, reloading.
[2022-12-10 12:35:13,264] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:18,079] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:24,469] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:27,853] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:32,517] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:34,222] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:40,450] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:42,443] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:46,091] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:49,440] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:35:55,138] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:03,040] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:13,861] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:15,061] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/models.py changed, reloading.
[2022-12-10 12:36:15,765] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:17,105] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:18,192] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:39,781] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:41,182] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:43,924] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:36:46,183] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:37:06,929] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:37:13,760] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:37:21,504] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:37:45,036] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:38:32,416] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:39:38,113] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:39:42,180] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10143
[2022-12-10 12:39:42,559] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 10143
[2022-12-10 12:39:43,875] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 16
[2022-12-10 12:39:44,926] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10143
[2022-12-10 12:39:45,022] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 10143
[2022-12-10 12:39:49,484] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 12:40:07,670] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:11,259] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:17,273] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:23,067] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:26,327] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:30,696] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:40,111] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:41,219] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:44,128] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:45,746] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:40:57,572] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'lude.exportData' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 17, in index
    data = exportData.objects.get(_id=list[0])
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'lude.exportData' doesn't exist")
[2022-12-10 12:40:57,580] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 196369
[2022-12-10 12:41:42,564] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:41:45,575] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:41:53,552] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:42:47,857] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:42:49,361] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:42:54,780] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 17, in index
    data = exportData.objects.get(_id=list[0])
NameError: name 'exportData' is not defined
[2022-12-10 12:42:54,786] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 56964
[2022-12-10 12:43:04,484] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:43:10,115] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'exportdata.id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 17, in index
    data = exportdata.objects.get(_id=list[0])
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'exportdata.id' in 'field list'")
[2022-12-10 12:43:10,122] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 196675
[2022-12-10 12:43:30,839] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:43:32,296] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:43:33,776] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:43:41,746] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:44:31,571] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:44:32,982] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:44:40,685] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'exportdata.id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 17, in index
    data = exportdata.objects.get(id=list[0])
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'exportdata.id' in 'field list'")
[2022-12-10 12:44:40,697] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 196356
[2022-12-10 12:46:49,155] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:46:52,746] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 17, in index
    data = exportdata.objects.get(id=list[0])
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
wxcloudrun.models.exportdata.DoesNotExist: exportdata matching query does not exist.
[2022-12-10 12:46:52,755] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 67122
[2022-12-10 12:47:38,929] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:47:45,285] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 17, in index
    data = exportdata.objects.get()
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
wxcloudrun.models.exportdata.MultipleObjectsReturned: get() returned more than one exportdata -- it returned more than 20!
[2022-12-10 12:47:45,291] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 68313
[2022-12-10 12:48:06,917] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:48:08,457] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:48:15,545] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:48:19,438] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 17, in index
    data = exportdata.objects.get().limit(5)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
wxcloudrun.models.exportdata.MultipleObjectsReturned: get() returned more than one exportdata -- it returned more than 20!
[2022-12-10 12:48:19,445] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 68331
[2022-12-10 12:48:25,609] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:48:52,494] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:48:56,229] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 17, in index
    data = exportdata.objects.get()
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
wxcloudrun.models.exportdata.MultipleObjectsReturned: get() returned more than one exportdata -- it returned more than 20!
[2022-12-10 12:48:56,235] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 68313
[2022-12-10 12:50:23,992] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:50:27,718] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:50:28,879] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:50:47,340] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:50:48,654] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:50:50,200] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:50:57,921] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 18, in index
    return JsonResponse({"status": True,"result":data})
  File "/root/.local/lib/python3.8/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
[2022-12-10 12:50:57,927] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 82998
[2022-12-10 12:52:01,786] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:52:07,490] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 18, in index
    return JsonResponse({"status": True,"result":data})
  File "/root/.local/lib/python3.8/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
[2022-12-10 12:52:07,495] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 83007
[2022-12-10 12:53:19,454] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:23,775] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 12:53:24,474] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:26,758] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 12:53:27,452] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:29,304] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:31,169] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:32,400] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 12:53:33,080] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:38,106] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 32
[2022-12-10 12:53:50,289] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:52,401] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:54,436] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:55,922] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:57,329] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:53:59,768] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:54:05,901] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 12:54:10,946] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 99
[2022-12-10 12:55:51,416] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 61
[2022-12-10 12:56:33,428] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 59
[2022-12-10 12:57:02,456] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 91
[2022-12-10 12:59:47,135] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 59
[2022-12-10 13:01:14,679] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 91
[2022-12-10 13:03:22,460] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 18, in index
    data = serializers.serialize("json", exportdata.objects.filter(id=list[0]).values())
TypeError: 'NoneType' object is not subscriptable
[2022-12-10 13:03:22,467] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 56634
[2022-12-10 13:03:31,613] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:03:32,808] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:03:33,450] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:03:40,560] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:03:44,739] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 42
[2022-12-10 13:04:08,591] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:04:13,413] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 20, in index
    return JsonResponse({"status": True,"result":data,"list":list})
  File "/root/.local/lib/python3.8/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WSGIRequest is not JSON serializable
[2022-12-10 13:04:13,421] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 82942
[2022-12-10 13:04:16,033] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 20, in index
    return JsonResponse({"status": True,"result":data,"list":list})
  File "/root/.local/lib/python3.8/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WSGIRequest is not JSON serializable
[2022-12-10 13:04:16,037] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 82942
[2022-12-10 13:04:25,429] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:04:29,408] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 42
[2022-12-10 13:04:39,925] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 99
[2022-12-10 13:04:49,087] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:04:54,323] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:04:56,793] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:04:59,213] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:05:02,029] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 89
[2022-12-10 13:05:51,875] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:05:56,820] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:05:59,900] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 97
[2022-12-10 13:06:08,564] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:06:09,953] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:06:13,214] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 18, in index
    data = serializers.serialize("json", exportdata.objects.filter(id=list[0]).values())
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/base.py", line 94, in serialize
    concrete_model = obj._meta.concrete_model
AttributeError: 'dict' object has no attribute '_meta'
[2022-12-10 13:06:13,220] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 69351
[2022-12-10 13:06:48,604] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:06:53,110] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 724
[2022-12-10 13:07:45,254] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:07:46,630] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:07:48,252] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:07:52,574] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:07:57,644] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:08:05,709] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 20, in index
    return JsonResponse({"status": True,"result":data,"list":list})
  File "/root/.local/lib/python3.8/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
[2022-12-10 13:08:05,716] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 84306
[2022-12-10 13:08:14,479] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:08:15,293] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:08:23,434] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 20, in index
    return JsonResponse({"status": True,"result":data,"list":list})
  File "/root/.local/lib/python3.8/site-packages/django/http/response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
[2022-12-10 13:08:23,440] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 89778
[2022-12-10 13:08:28,719] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:08:29,721] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:08:54,072] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:09:28,167] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:09:30,614] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:10:41,743] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:10:43,850] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:10:48,432] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:10:50,626] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:10:53,309] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:10:56,879] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:11:02,527] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 724
[2022-12-10 13:11:54,944] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:11:58,719] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 18, in index
    data = serializers.serialize("json", exportdata.objects.filter(id=list[0])).all()
AttributeError: 'str' object has no attribute 'all'
[2022-12-10 13:11:58,726] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57199
[2022-12-10 13:12:08,729] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:12:13,187] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 724
[2022-12-10 13:12:31,453] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:12:36,243] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 18, in index
    data = serializers.serialize("json", exportdata.objects.filter(id=list[0]).values())
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/root/.local/lib/python3.8/site-packages/django/core/serializers/base.py", line 94, in serialize
    concrete_model = obj._meta.concrete_model
AttributeError: 'dict' object has no attribute '_meta'
[2022-12-10 13:12:36,247] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 69347
[2022-12-10 13:12:45,392] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:12:49,510] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:12:52,273] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:12:57,383] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 724
[2022-12-10 13:13:06,117] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:13:09,761] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:13:13,315] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 18, in index
    data = serializers.serialize("json", exportdata.objects.filter(id=list[0]).fields)
AttributeError: 'QuerySet' object has no attribute 'fields'
[2022-12-10 13:13:13,321] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57233
[2022-12-10 13:13:19,641] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:13:21,846] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:13:25,085] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 18, in index
    data = serializers.serialize("json", exportdata.objects.filter(id=list[0]).fields())
AttributeError: 'QuerySet' object has no attribute 'fields'
[2022-12-10 13:13:25,090] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57237
[2022-12-10 13:13:39,109] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:13:52,079] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:16:14,716] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:16:21,613] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:16:23,863] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:16:30,053] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:16:33,611] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 309, in check_response
    raise ValueError(
ValueError: The view wxcloudrun.views.index didn't return an HttpResponse object. It returned None instead.
[2022-12-10 13:16:33,612] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57840
[2022-12-10 13:16:49,072] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:16:50,800] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:16:54,793] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:17:12,065] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:17:15,306] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:17:22,780] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:17:27,985] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:17:32,822] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:17:40,746] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:17:42,875] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:17:44,591] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:17:46,187] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:17:53,637] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:18:04,915] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:18:08,556] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:18:14,438] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:18:15,646] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:18:16,625] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:18:20,562] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:19:55,631] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:20:10,157] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:20:10,865] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:20:15,084] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:20:15,807] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:20:23,350] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:20:33,508] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:20:36,824] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:20:37,508] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:20:42,697] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 20, in index
    print(item.value)
AttributeError: 'exportdata' object has no attribute 'value'
[2022-12-10 13:20:42,702] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57650
[2022-12-10 13:20:51,278] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:22:34,407] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:22:37,746] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:22:39,857] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:23:12,819] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:23:15,096] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:23:21,402] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:23:26,840] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:23:37,686] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:23:42,749] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:23:45,800] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 83
[2022-12-10 13:23:54,979] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:24:03,088] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:24:05,290] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:24:13,621] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:24:16,717] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:24:18,498] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:24:21,703] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 20, in index
    for temp in item:
TypeError: 'exportdata' object is not iterable
[2022-12-10 13:24:21,707] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57660
[2022-12-10 13:24:29,246] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:25:21,250] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:25:23,763] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:25:24,848] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:25:25,985] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:26:58,654] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:27:25,353] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:27:26,061] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:28:21,048] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:28:48,684] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:34:24,260] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:34:34,808] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:38:26,175] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:38:31,245] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10143
[2022-12-10 13:38:31,510] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 10143
[2022-12-10 13:38:35,013] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:38:37,226] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:39:32,403] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:39:34,505] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:39:37,023] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:39:50,826] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:39:54,415] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:39:57,956] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:40:00,004] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:40:45,145] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:40:46,577] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:40:49,604] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:40:59,952] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:01,147] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:05,080] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:08,487] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:10,083] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:11,920] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:13,388] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:20,369] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:22,003] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:23,958] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:25,490] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:29,683] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:41:35,368] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 13:42:01,686] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:42:02,435] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:43:48,566] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:43:52,263] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:43:55,265] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 21, in index
    current_time = datetime.datetime.now().strftime( '%Y-%m-%d %H:%M:%S %f' )
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-12-10 13:43:55,271] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57084
[2022-12-10 13:44:05,032] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:44:06,093] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:44:08,408] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:44:09,478] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:44:11,560] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 13:44:28,352] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:44:33,522] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:44:40,143] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:44:51,905] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 13:45:11,091] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:45:13,300] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:45:15,549] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:45:53,989] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:45:58,084] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:03,691] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:11,536] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:14,044] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:21,051] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:27,474] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:39,209] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:41,359] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:52,573] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:46:54,561] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:47:04,611] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:47:08,899] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:47:12,041] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:47:28,642] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:47:32,359] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:47:53,221] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:47:59,389] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:48:01,295] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:48:08,333] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:48:14,527] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:48:21,937] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:48:22,638] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:48:47,602] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:48:52,498] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:48:59,995] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:49:43,290] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:49:48,423] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:49:56,738] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:49:58,295] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:12,747] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:14,661] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:17,551] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:20,192] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:23,077] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:26,701] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:35,157] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:50:35,795] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:42,056] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:46,109] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:48,901] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:54,044] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:50:58,259] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:05,440] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:07,939] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:22,109] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:26,456] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:29,474] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:35,709] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:39,566] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:45,401] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:48,359] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:53,109] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:56,323] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:51:59,712] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:52:05,637] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:52:08,259] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:52:13,174] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:52:18,528] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 13:52:19,221] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:52:20,506] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:52:26,393] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:52:32,331] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:52:53,507] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:02,815] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:04,073] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:06,701] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:13,080] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:16,784] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:18,986] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:39,386] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:45,335] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:48,531] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:55,820] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:53:58,933] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:00,553] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:07,305] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:08,489] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:09,473] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:16,148] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:19,788] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:23,870] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:28,540] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:32,437] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 22, in index
    dest_filename = settings.BASE_DIR + '\\doc_tmp\\' + file_name
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
[2022-12-10 13:54:32,446] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 57938
[2022-12-10 13:54:57,640] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:54:59,634] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:55:04,070] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 34, in index
    row = list(row)
TypeError: 'list' object is not callable
[2022-12-10 13:55:04,078] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 59601
[2022-12-10 13:55:29,599] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:55:33,566] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 13:55:44,825] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:55:46,367] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:55:50,684] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:55:56,745] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:56:00,688] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 13:56:08,053] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:56:12,065] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:56:16,014] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 13:56:32,333] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:56:33,922] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:56:37,360] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 34, in index
    row = list(row)
TypeError: 'list' object is not callable
[2022-12-10 13:56:37,370] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 60745
[2022-12-10 13:57:54,034] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:57:57,593] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:58:04,170] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:58:13,204] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:58:17,890] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 13:58:24,909] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:58:35,297] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:58:37,414] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:58:39,693] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:58:44,607] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:59:31,242] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:59:35,333] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:59:48,590] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 13:59:54,275] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:00:04,337] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:00:08,297] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:00:15,095] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:01:11,990] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:01:14,547] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:01:18,143] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:02:02,448] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:02:26,413] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:02:27,215] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:02:32,916] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:02:39,138] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:02:47,090] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:02:53,640] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:03:56,039] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:04:02,486] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:04:25,322] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:04:26,675] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:04:27,908] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 14:04:28,798] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:04:34,613] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:04:42,547] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:04:48,425] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:05:16,396] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:05:17,647] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:05:19,989] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:05:21,717] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:05:34,555] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:05:36,130] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:05:41,982] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:06:06,997] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:09,384] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:18,693] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:22,430] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:23,843] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:27,654] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:29,132] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:31,986] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:36,641] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:06:51,255] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:52,759] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:06:54,681] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:07:02,192] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:07:04,615] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:07:24,483] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:07:25,637] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:07:27,733] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:07:28,948] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 14:07:29,669] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:07:31,364] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:08:14,069] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:08:16,322] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:08:32,721] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:08:39,563] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 16
[2022-12-10 14:08:47,703] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:08:50,005] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:08:55,194] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:04,075] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:05,822] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:07,346] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:10,744] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:12,343] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:13,747] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:17,066] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:18,733] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:34,805] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:38,068] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:40,479] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:45,984] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:50,568] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:53,201] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:09:54,482] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:05,409] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:07,251] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:11,248] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:14,217] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:16,431] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:20,136] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:23,052] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:28,163] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:31,238] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:32,846] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:37,081] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:42,090] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:45,220] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:46,683] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:50,269] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:51,926] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:53,418] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:57,145] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:10:59,308] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:00,782] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:05,531] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:08,263] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:09,847] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:14,047] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:16,318] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:18,244] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:27,310] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:35,568] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:43,219] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:44,946] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:49,776] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:11:53,499] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:25:54,215] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:25:55,443] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 14:25:56,100] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:25:57,998] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:26:00,286] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:26:19,283] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:26:21,152] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:26:49,764] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:26:52,700] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:26:54,973] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- /app/wxcloudrun/views.py changed, reloading.
[2022-12-10 14:26:55,685] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:26:59,264] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:01,793] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:18,576] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:24,107] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:25,417] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:27,184] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:29,826] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:32,568] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:35,771] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:39,576] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:45,970] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:53,373] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:27:57,382] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:28:03,819] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:28:05,407] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:28:09,626] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:28:11,126] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:28:24,643] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 62, in index
    excel = open(dest_filename,"rb")
FileNotFoundError: [Errno 2] No such file or directory: '/app\\doc_tmp\\志愿表20221210142822260366.xlsx'
[2022-12-10 14:28:24,649] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 61081
[2022-12-10 14:29:10,941] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:29:12,723] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:29:21,176] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 62, in index
    excel = open(dest_filename,"rb")
FileNotFoundError: [Errno 2] No such file or directory: '.\\doc_tmp\\志愿表20221210142919653259.xlsx'
[2022-12-10 14:29:21,182] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 61069
[2022-12-10 14:29:27,138] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:29:29,133] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:29:41,068] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:29:43,500] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:29:52,014] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 62, in index
    excel = open(dest_filename,"rb")
FileNotFoundError: [Errno 2] No such file or directory: '.\\doc_tmp\\志愿表20221210142950099059.xlsx'
[2022-12-10 14:29:52,020] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 61069
[2022-12-10 14:30:16,862] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:30:19,208] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:30:23,126] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 6011
[2022-12-10 14:30:45,408] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:30:50,263] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 21, in index
    dest_filename = settings.BASE_DIR + '\\doc_tmp\\' + file_name
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
[2022-12-10 14:30:50,269] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 58107
[2022-12-10 14:31:02,727] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:31:04,327] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:31:05,709] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:31:17,751] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 6011
[2022-12-10 14:31:37,496] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:31:40,211] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:32:39,847] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:32:44,912] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:32:47,803] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:32:55,338] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 6012
[2022-12-10 14:33:00,799] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:33:04,384] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 70, in index
    excel = open(dest_filename,"rb")
FileNotFoundError: [Errno 2] No such file or directory: '/app\\doc_tmp\\志愿表20221210143302865481.xlsx'
[2022-12-10 14:33:04,390] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST / HTTP/1.1" 500 61383
[2022-12-10 14:33:11,139] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:33:42,281] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:34:07,928] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:34:13,084] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 6011
[2022-12-10 14:34:41,651] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:34:43,756] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:34:50,971] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:34:53,728] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:34:56,397] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:34:57,674] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:34:58,442] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:35:05,862] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 6012
[2022-12-10 14:35:41,469] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:35:43,947] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:36:16,888] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 6011
[2022-12-10 14:36:30,136] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 14:37:25,973] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
